# Generated by Django 3.2.4 on 2021-07-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(default='projects/default.jpg', upload_to='projects'),
        ),
    ]
